### ISSUE TITLE
partNumber fails for multipart/related within message/rfc822 message

### ISSUE THREAD

**Issue by geoffreybennett** [markov2/perl5-Mail-Message#13]
Minimal test case:

```
#!/usr/bin/perl

use Mail::Message;

print((Mail::Message->read(<<'END')->parts)[0]->partNumber, "\n");
Content-Type: message/rfc822

Content-Type: multipart/related; boundary="x"

--x
Content-Length: 0

--x--
END
```
Output:
```
Use of uninitialized value in concatenation (.) or string at /usr/share/perl5/vendor_perl/Mail/Message/Body/Multipart.pm line 412.
.1
```
That's this line, which assumes that `$msg->partNumber` is always defined:
https://github.com/markov2/perl5-Mail-Message/blob/add522ea7d09e5e88c92720415ee957d5d3789ab/lib/Mail/Message/Body/Multipart.pm#L571

I'm using the current release 3.012:
```
$ grep '^$VERSION' /usr/share/perl5/vendor_perl/Mail/Message/Body/Multipart.pm
$VERSION = '3.012';
```

**Comment by markov2** [comment]
The problem was caused by the reuse of '::Part': it cannot only be one of the parts of multipart, but also the single child of a message/rfc822.  The latter was expected always to be a child of a multipart itself, not the top of a message. (Forgot issue number in commit)  Patch: 4d78af3d461ab5e99106b62c7018a311e4b7b32a

Thanks for your report.
